### ISSUE TITLE
Quotes and Rates extension table exception on MD2021.1

### ISSUE THREAD

**Issue by sreilly** [TheInfiniteKind/moneydance_open#19]
`yahooqt` is throwing an exception that prevents display of the main quotes and rates settings window. This issue is important for the 2021.1 release because the extension is bundled with the mac app store version of moneydance.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JTable.getTableHeader()" because "table" is null
	at com.moneydance.modules.features.yahooqt.SettingsWindow$UseColumnHeaderRenderer.getTableCellRendererComponent(SettingsWindow.java:767)
	at org.violetlib.aqua.AquaTableHeaderUI.getHeaderRendererAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.getHeaderHeightAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.createHeaderSizeAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.table.JTableHeader.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ViewportLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ScrollPaneLayout.preferredLayoutSize(Unknown Source)
	at org.violetlib.aqua.AquaOverlayScrollPaneLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JRootPane$RootLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/java.awt.Window.pack(Unknown Source)
	at com.moneydance.modules.features.yahooqt.SettingsWindow.<init>(SettingsWindow.java:94)
	at com.moneydance.modules.features.yahooqt.Main$1.run(Main.java:182)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JTable.getTableHeader()" because "table" is null
	at com.moneydance.modules.features.yahooqt.SettingsWindow$UseColumnHeaderRenderer.getTableCellRendererComponent(SettingsWindow.java:767)
	at org.violetlib.aqua.AquaTableHeaderUI.getHeaderRendererAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.getHeaderHeightAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.createHeaderSizeAqua(Unknown Source)
	at org.violetlib.aqua.AquaTableHeaderUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.table.JTableHeader.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ViewportLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ScrollPaneLayout.preferredLayoutSize(Unknown Source)
	at org.violetlib.aqua.AquaOverlayScrollPaneLayout.preferredLayoutSize(Unknown Source)
	at java.desktop/java.awt.Container.preferredSize(Unknown Source)
	at java.desktop/java.awt.Container.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.ArrangeGrid(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.arrangeGrid(Unknown Source)
	at java.desktop/java.awt.GridBagLayout.layoutContainer(Unknown Source)
	at java.desktop/java.awt.Container.layout(Unknown Source)
	at java.desktop/java.awt.Container.doLayout(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validate(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by sreilly** [comment]
This is fixed in the current version of the quotes and rates extension
