### ISSUE TITLE
BUG with Bank Direct Connections - using proxy when proxy is not enabled...

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#58]
A user has reported an issue when connecting to USAA (and my custom profile). It works for him in build 1929, but in build 3069 it fails.  NOTE - this is not just a usaa problem. I believe it will go wrong for all downloads.

He noticed this in the log:
java.lang.IllegalArgumentException: type DIRECT is not compatible with address 127.0.0.1/<unresolved>:8866 
at java.base/java.net.Proxy.<init>(Unknown Source)

...and he is NOT using a proxy. Specifically, net.proxy_host was set to 127.0.0.1 and net.proxy_port was set to 8866. HOWEVER, net.use_proxy was NOT set and in preferences it was NOT ticked. (He could see the other settings there, but greyed out).

I noticed that com.moneydance.apps.md.controller.olb.HttpsHelper.getProxyConnection() does check net.use_proxy, but also that com.moneydance.apps.md.controller.olb.CustomURLStreamHandlerFactory.HttpURLConnectionImpl() does NOT check net.use_proxy; it simply checks for net.proxy_host being set.

I have no idea if the method above is used in creating the bank connection, but regardless it looks like MD is using the net.proxy_host setting even if the net.use_proxy is not set.

This might explain other similar issues raised by others in the past.

Sorry, I have no way to test.

**Comment by yogi1967** [comment]
In fact, I can test it.... and yes, this is the problem! If the proxy data is set, even if the use proxy field is NOT set, then direction connection fails... Delete the data and it doesn't fail:.

```
There was an error communicating with your financial institution.  The details of this error are below.

Bank Name: USAA Custom Profile (ofx_create_new_usaa_bank_profile_custom.py)
Account: USAA CC2
Account Number: 1111222211113334

I'm sorry, an error occurred.  The details of this error are below.
Error Description: java.lang.IllegalArgumentException: type DIRECT is not compatible with address 127.0.0.1/<unresolved>:8866
java.lang.IllegalArgumentException: type DIRECT is not compatible with address 127.0.0.1/<unresolved>:8866
	at java.base/java.net.Proxy.<init>(Unknown Source)
	at com.moneydance.apps.md.controller.olb.CustomURLStreamHandlerFactory$HttpURLConnectionImpl.<init>(CustomURLStreamHandlerFactory.java:245)
	at com.moneydance.apps.md.controller.olb.CustomURLStreamHandlerFactory$HttpsURLConnectionImpl.<init>(CustomURLStreamHandlerFactory.java:709)
	at com.moneydance.apps.md.controller.olb.CustomURLStreamHandlerFactory$HttpsURLConnectionHandler.openConnection(CustomURLStreamHandlerFactory.java:202)
	at com.moneydance.apps.md.controller.olb.CustomURLStreamHandlerFactory.openConnection(CustomURLStreamHandlerFactory.java:156)
	at com.moneydance.apps.md.controller.olb.HttpsHelper2.getOFXConnection(HttpsHelper2.java:278)
	at com.moneydance.apps.md.controller.olb.ofx.OFXConnection.sendMessage(OFXConnection.java:2620)
	at com.moneydance.apps.md.controller.olb.ofx.OFXConnection.sendMessage(OFXConnection.java:2564)
	at com.moneydance.apps.md.controller.olb.ofx.OFXConnection.getTransactions(OFXConnection.java:973)
	at com.moneydance.apps.md.view.gui.OnlineManager.downloadTransactions(OnlineManager.java:550)
	at com.moneydance.apps.md.view.gui.OnlineManager.downloadTransactions(OnlineManager.java:465)
	at com.moneydance.apps.md.view.gui.AccountDetailPanel.lambda$downloadTransactions$0(AccountDetailPanel.java:296)
	at com.moneydance.apps.md.controller.BackgroundOpsThread.run(BackgroundOpsThread.java:136)
```

**Comment by sreilly** [comment]
DIRECT means no proxy should be used, but the proxy settings are set to point to 127.0.0.1 which is your computer. It sounds like we may be checking the proxy host from the settings and possibly using it even if the Proxy checkbox is disabled. I'll fix this, but in the meantime please can you delete the contents of the proxy host field in the preferences?

**Comment by yogi1967** [comment]
Yes. Exactly. The proxy is being used even if the use proxy field is not ticked. I’ve proven it. Yes, deleting the data fixes the problem.

**Comment by sreilly** [comment]
This is fixed for the next preview
